### ISSUE TITLE
IRC clients lose some messages right after disconnect

### ISSUE THREAD

**Issue by yuvipanda** [42wim/matterircd#11] opened 2015-11-19 20:56 UTC
In the following log, user @halfak was on IRC and user @yuvipanda was on the mattermost web interface. 'yuvipanda' sent numbers from 1 to 30, and 2-6 were missed...

    [13:10:27] <yuvipanda> @halfak ok next
    [13:10:36] <yuvipanda> @halfak is the 1 to 30 disconnection thing
    [13:10:45] <halfak> OK.  Ready to disconnect
    [13:10:52] <yuvipanda> 1
    [13:10:55] <yuvipanda> @halfak go! :)
    [13:10:56] <yuvipanda> 2
    [13:10:59] * Disconnected ()
    [13:11:22] * Now talking on #town-square
    [13:11:22] * subbu (3j5u8mfb57rg8c3dsozno8a1qh@https://mattermost.wmflabs.org) has joined
    [13:11:22] * tgr (6ezx1bib83898dh6x9g3cz71iw@https://mattermost.wmflabs.org) has joined
    [13:11:22] * joe (akr6t7k3ubdhmnit96cazh1xth@https://mattermost.wmflabs.org) has joined
    [13:11:22] * robla (idxrsxk1ubd95p4pjq83rqzu4e@https://mattermost.wmflabs.org) has joined
    [13:11:22] * luisv (n5fbhrmwwibifjaerouxqracyr@https://mattermost.wmflabs.org) has joined
    [13:11:22] * stu (pgj4t7yuffbq3xdks773kijqdc@https://mattermost.wmflabs.org) has joined
    [13:11:22] * hashar (tfr5g9rscj8hxbazod4qrcaibr@https://mattermost.wmflabs.org) has joined
    [13:11:22] <yuvipanda> 6
    [13:11:22] <yuvipanda> 7
    [13:11:22] <yuvipanda> 8
    [13:11:22] <yuvipanda> 9
    [13:11:22] <yuvipanda> 10
    [13:11:22] <yuvipanda> 11
    [13:11:22] <yuvipanda> 12
    [13:11:22] <yuvipanda> 13
    [13:11:22] <yuvipanda> 14
    [13:11:22] <yuvipanda> 15
    [13:11:22] <yuvipanda> 16
    [13:11:22] <yuvipanda> 17
    [13:11:22] <yuvipanda> 18
    [13:11:22] <yuvipanda> 19
    [13:11:22] <yuvipanda> 20
    [13:11:22] <yuvipanda> 21
    [13:11:22] <yuvipanda> 22
    [13:11:22] <yuvipanda> 23
    [13:11:23] <yuvipanda> 24
    [13:11:24] <yuvipanda> 25
    [13:11:25] <yuvipanda> 26
    [13:11:26] <yuvipanda> 27
    [13:11:26] <halfak> Back
    [13:11:27] <yuvipanda> 28
    [13:11:32] <yuvipanda> @halfak what did you see
    [13:11:43] <halfak> So, it looks like 2-6 dropped.

**Comment by 42wim** [comment] 2015-11-19 21:18
Can't reproduce it, probably can't type fast enough. Is it possible to try again with -debug on ?
Pipe it through ```grep -v "PRIVMSG mattermost :LOGIN"``` so that you're credentials aren't visible.

**Comment by yuvipanda** [comment] 2015-11-19 21:34
I already had debug on for this so let me find the logs.

**Comment by 42wim** [comment] 2015-11-28 22:35
Any logs or reproduced again ? otherwise I'll close this.

**Comment by yuvipanda** [comment] 2015-11-28 23:23
I'll try repro this the coming week whwen more of my victims come back
online from vacation

On Sat, Nov 28, 2015 at 2:35 PM, @42wim <notifications@github.com> wrote:

> Any logs or reproduced again ? otherwise I'll close this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/42wim/matterircd/issues/11#issuecomment-160343097>.
>



-- 
Yuvi Panda T
http://yuvi.in/blog

**Comment by 42wim** [comment] 2015-12-22 20:35
ping timeout, reopen when it happens again :-)

**Closed by 42wim** 2015-12-22 20:35 UTC
Labels: waiting for feedback
