### ISSUE TITLE
100% cpu usage

### ISSUE THREAD

**Issue by flexd** [42wim/matterircd#223] opened 2019-01-25 09:36 UTC
Hi there.

I started matterircd using the Docker container, and it works fine `sudo docker run -d --name matterircd -p 6667:6667 42wim/matterircd:latest -bind 0.0.0.0:6667`
but I just noticed that matterircd is pinned to 100% cpu, which is a problem since this little droplet only has 1 core and also seems completely pointless.

Doing a strace of the process reveals it looks to be polling something tens of thousands of times per second. This is a small excerpt:
```
[pid  8645] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid  8755] epoll_pwait(4,  <unfinished ...>
[pid  8645] <... nanosleep resumed> NULL) = 0
[pid  8645] futex(0x56527f09ef90, FUTEX_WAIT_PRIVATE, 0, {tv_sec=60, tv_nsec=0} <unfinished ...>
[pid  8755] <... epoll_pwait resumed> [], 128, 0, NULL, 33555305579222796) = 0
[pid  8755] futex(0x56527f09ef90, FUTEX_WAKE_PRIVATE, 1) = 1
[pid  8645] <... futex resumed> )       = 0
[pid  8645] sched_yield()               = 0
[pid  8645] futex(0x56527f09eeb0, FUTEX_WAKE_PRIVATE, 1) = 0
[pid  8645] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid  8755] futex(0xc00002e840, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid  8645] <... nanosleep resumed> NULL) = 0
[pid  8645] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid  8755] <... futex resumed> )       = 1
[pid  8646] <... futex resumed> )       = 0
[pid  8646] epoll_pwait(4,  <unfinished ...>
[pid  8645] <... nanosleep resumed> NULL) = 0
[pid  8645] futex(0x56527f09ef90, FUTEX_WAIT_PRIVATE, 0, {tv_sec=60, tv_nsec=0} <unfinished ...>
[pid  8646] <... epoll_pwait resumed> [], 128, 0, NULL, 33555305593471377) = 0
[pid  8646] futex(0x56527f09ef90, FUTEX_WAKE_PRIVATE, 1) = 1
[pid  8645] <... futex resumed> )       = 0
[pid  8645] sched_yield()               = 0
[pid  8645] futex(0x56527f09eeb0, FUTEX_WAIT_PRIVATE, 2, NULL <unfinished ...>
[pid  8755] futex(0x56527f0a2fc0, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=30231115} <unfinished ...>
[pid  8646] futex(0x56527f09eeb0, FUTEX_WAKE_PRIVATE, 1) = 1
[pid  8645] <... futex resumed> )       = 0
[pid  8646] epoll_pwait(4,  <unfinished ...>
[pid  8645] futex(0x56527f09eeb0, FUTEX_WAKE_PRIVATE, 1) = 0
[pid  8645] epoll_pwait(4, [], 128, 0, NULL, 33555305601673686) = 0
[pid  8645] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid  8646] <... epoll_pwait resumed> [], 128, 0, NULL, 33555305600979186) = 0
[pid  8645] <... nanosleep resumed> NULL) = 0
```

What's going on here? I have not dived into the Matterircd code here yet, but will in a second.

**Comment by 42wim** [comment] 2019-01-25 11:06
so you just run the docker command above and it takes 100% CPU ? Nothing else happens, like connections to matterircd or so?

**Comment by flexd** [comment] 2019-01-25 11:59
Matterircd works fine. I can connect to it, I am connected to Mattermost through it. It's not a very busy mattermost (like 10 channels and not a lot of activity). Seems like it's working as intended other than the high cpu usage

**Comment by 42wim** [comment] 2019-01-25 14:04
That's very strange, run with `-debug` and see if something is going on there.
What mattermost version?

**Comment by flexd** [comment] 2019-01-31 10:49
I am only connected to two teams (same server), and the message volume is not that high.

**Comment by flexd** [comment] 2019-01-31 10:55
I suspect this is the culprit: 

https://github.com/42wim/matterircd/blob/84eecb73c04635add932d30fb1f2b20be41452fc/mm-go-irckit/user.go#L195

**Comment by flexd** [comment] 2019-02-03 09:38
> I suspect this is the culprit:
> 
> [matterircd/mm-go-irckit/user.go](https://github.com/42wim/matterircd/blob/84eecb73c04635add932d30fb1f2b20be41452fc/mm-go-irckit/user.go#L195)
> Line 195 in [84eecb7](/42wim/matterircd/commit/84eecb73c04635add932d30fb1f2b20be41452fc)
>  msg, err := user.Conn.Decode()

That isn't it ^, and I have no idea why I thought so. Compiling matterircd myself and not running the docker container seems to have resolved the problem.

**Comment by 42wim** [comment] 2019-02-05 20:05
can't seem to reproduce this and as your problem is solved by not using docker, going to close this for now :)

**Closed by 42wim** 2019-02-05 20:05 UTC

**Comment by pbui** [comment] 2019-02-09 02:56
I too am having the problem of 100% CPU usage, which adds a lot of latency to matterircd (built it from source, not using docker, only 3-5 users).  Here is a snapshot from pprof:

```
Showing nodes accounting for 1.13s, 3.88% of 29.14s total
Dropped 29 nodes (cum <= 0.15s)
Showing top 5 nodes out of 32
      flat  flat%   sum%        cum   cum%
     0.03s   0.1%   0.1%     29.08s 99.79%  github.com/42wim/matterircd/mm-go-irckit.(*User).Decode
     0.30s  1.03%  1.13%        29s 99.52%  github.com/42wim/matterircd/vendor/github.com/sorcix/irc.(*Decoder).Decode
     0.16s  0.55%  1.68%     28.03s 96.19%  bufio.(*Reader).ReadString
     0.33s  1.13%  2.81%     27.83s 95.50%  bufio.(*Reader).ReadBytes
     0.31s  1.06%  3.88%     27.09s 92.96%  bufio.(*Reader).ReadSlice
```

The gateway still works, but it is very slow and bogs down the server.

**Comment by pbui** [comment] 2019-02-09 02:59
![Call Graph](https://i.imgur.com/mlpmQMv.png)

**Comment by pbui** [comment] 2019-02-09 03:13
Note, I had set `PasteBufferTimeout = 0` because the latency was so bad and perhaps this exacerbated the problem.

I just rolled back to v0.18.4 and I am not noticing the same 100% CPU usage.
