### ISSUE TITLE
Direct messages from Limechat have no content

### ISSUE THREAD

**Issue by teetrinkers** [42wim/matterircd#20] opened 2015-12-22 14:58 UTC
Hi, I'm using matterircd build from master with Mattermost 1.3.0. There is some weird behaviour when posting messages using an IRC client.

Example 1:
* User A using IRC client posts a direct message to user B using the Mattermost web client.
* The Mattermost client of user B shows a new message but without any text.

Example 2:
* User A posts "hubot ping" using an IRC client to a public channel which has a hubot.
* Other users (using the Mattermost web client) can see the message in the channel, but hubot doesn't respond.
* User A posts "hubot ping" using the Mattermost web client to the public channel.
* Hubot responds with "PONG".

Do you have any idea?

**Comment by 42wim** [comment] 2015-12-22 20:34
Example 1: Can not reproduce it with irssi, what IRC client do you use ?
Example 2: That could maybe be because there is a 'hidden' UTF-8 code send with every message from IRC.

Every message from an IRC user has a 'http://www.fileformat.info/info/unicode/char/180e/fontsupport.htm' character added. So that we can distinguish if a message came from IRC or from mattermost, so that there is no 'double echo' when you type your message on IRC. 

If the hubot script does an exact match this could happen. 

I don't have an option to test it, but you can by removing this line (https://github.com/42wim/mm-go-irckit/blob/master/server.go#L777) from GOPATH/src/github.com/42wim/mm-go-irckit/server.go and rebuild. (You'll get echo's on IRC now though)

**Comment by teetrinkers** [comment] 2015-12-23 10:59
Example 1:
I used Limechat. Strangely, I can not reproduce it with irssi. It seems Limechat is doing something strange that matterircd doesn't like. I think after christmas I will have some time to look at the source and debug this.

Example 2:
Yeah, "hubot ping" probably does an exact match. So that's cleared up :)

**Comment by 42wim** [comment] 2016-02-10 19:54
@teetrinkers Any updates? otherwise closing for now.

**Comment by teetrinkers** [comment] 2016-02-11 12:20
Sorry for not getting back to you. So far, Limechat is the only client I have found which does not work with matterircd. My coworkers use Miranda, which works well, therefore I haven't investigated the problems with Limechat any further.

**Comment by 42wim** [comment] 2016-02-11 17:32
OK thanks, closing now :)

**Closed by 42wim** 2016-02-11 17:32 UTC
Labels: waiting for feedback
