### ISSUE TITLE
Crash at /msg mattermost search

### ISSUE THREAD

**Issue by xyproto** [42wim/matterircd#31] opened 2016-02-09 09:02 UTC
Hi,

This is using the latest master branch (commit aec9b497b7f0e10a91a4b5b3229eb38c5b0387a5).

go 1.5.3 on 64-bit Arch Linux.

Here is a log of the crash:

```
./matterircd --debug=true --interface="server" --mmserver="mattermost" --mmteam="team" --port=6667           
2016-02-09 09:55:49.736 INFO enabling debug
2016-02-09 09:56:50.023 INFO New connection: 10.10.48.238:36204
2016-02-09 09:56:50.026 DEBUG <- NICK afr
2016-02-09 09:56:50.026 DEBUG <- USER afr 0 * :afr
2016-02-09 09:56:50.026 DEBUG -> :matterircd 001 afr :Welcome! afr!afr@server
2016-02-09 09:56:50.026 DEBUG -> :matterircd 002 afr :Your host is matterircd, running version 0.2
2016-02-09 09:56:50.026 DEBUG -> :matterircd 003 afr :This server was created Tue Feb  9 09:56:50 CET 2016
2016-02-09 09:56:50.026 DEBUG -> :matterircd 004 afr :matterircd 0.2 o o
2016-02-09 09:56:50.026 DEBUG -> :matterircd 251 afr :There are 2 users and 0 services on 1 servers
2016-02-09 09:56:50.026 DEBUG -> :matterircd 375 afr :- matterircd Message of the Day -
2016-02-09 09:56:50.026 DEBUG -> :matterircd 376 afr :End of /MOTD command.
2016-02-09 09:57:04.578 DEBUG <- LIST
2016-02-09 09:57:04.578 DEBUG -> :matterircd 321 afr :Channel Users Topic
2016-02-09 09:57:04.578 DEBUG -> :matterircd 323 afr :End of /LIST
2016-02-09 09:57:21.530 DEBUG <- PRIVMSG mattermost :login mattermost afr password
2016-02-09 09:57:21.530 DEBUG -> :mattermost!mattermost@service PRIVMSG afr :need LOGIN <login> <pass>
2016-02-09 09:57:32.044 DEBUG <- PRIVMSG mattermost :search queryt
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x590727]

goroutine 9 [running]:
github.com/mattermost/platform/model.(*Client).DoApiGet(0x0, 0xc820013f80, 0x1a, 0x0, 0x0, 0x0, 0x0, 0x7, 0x0)
	/home/afr/go/src/github.com/mattermost/platform/model/client.go:84 +0x517
github.com/mattermost/platform/model.(*Client).SearchPosts(0x0, 0xc8200e106b, 0x6, 0x2, 0x2)
	/home/afr/go/src/github.com/mattermost/platform/model/client.go:747 +0xc4
github.com/42wim/mm-go-irckit.(*User).searchMMPosts(0xc8200d4d00, 0xc8200e106b, 0x6, 0x91c2c0)
	/home/afr/go/src/github.com/42wim/mm-go-irckit/mmuser.go:651 +0x3d
github.com/42wim/mm-go-irckit.(*User).handleMMServiceBot(0xc8200d4d00, 0xc8200d4dd0, 0xc8200e1064, 0xd)
	/home/afr/go/src/github.com/42wim/mm-go-irckit/mmuser.go:538 +0x113d
created by github.com/42wim/mm-go-irckit.(*server).handle
	/home/afr/go/src/github.com/42wim/mm-go-irckit/server.go:783 +0x520a

goroutine 1 [IO wait]:
net.runtime_pollWait(0x7f5a16f55c38, 0x72, 0xc82000e200)
	/usr/lib/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82010ced0, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82010ced0, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc82010ce70, 0x0, 0x7f5a16f55cf8, 0xc820013d80)
	/usr/lib/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc820030108, 0xc820103d70, 0x0, 0x0)
	/usr/lib/go/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc820030108, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/tcpsock_posix.go:264 +0x3d
main.start(0x7f5a16f54c90, 0xc820030108)
	/home/afr/checkout/matterircd/main.go:46 +0x4e
main.main()
	/home/afr/checkout/matterircd/main.go:41 +0x8a9

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 5 [chan receive]:
github.com/alecthomas/log4go.(*ConsoleLogWriter).run(0xc820012760, 0x7f5a16f54330, 0xc820030010)
	/home/afr/go/src/github.com/alecthomas/log4go/termlog.go:33 +0x69
created by github.com/alecthomas/log4go.NewConsoleLogWriter
	/home/afr/go/src/github.com/alecthomas/log4go/termlog.go:26 +0xb5

goroutine 7 [IO wait]:
net.runtime_pollWait(0x7f5a16f55b78, 0x72, 0xc82000e200)
	/usr/lib/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82010cf40, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82010cf40, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82010cee0, 0xc820113000, 0x1000, 0x1000, 0x0, 0x7f5a16f50050, 0xc82000e200)
	/usr/lib/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820030110, 0xc820113000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/net.go:172 +0xe4
bufio.(*Reader).fill(0xc82000a900)
	/usr/lib/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0xc82000a900, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/bufio/bufio.go:328 +0x21a
bufio.(*Reader).ReadBytes(0xc82000a900, 0xc820013e0a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/bufio/bufio.go:406 +0xa9
bufio.(*Reader).ReadString(0xc82000a900, 0x7d8e0a, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/bufio/bufio.go:446 +0x4d
github.com/sorcix/irc.(*Decoder).Decode(0xc820013e00, 0x0, 0x0, 0x0)
	/home/afr/go/src/github.com/sorcix/irc/stream.go:80 +0x59
github.com/42wim/mm-go-irckit.(*User).Decode(0xc8200d4d00, 0x9f1b18, 0x0, 0x0)
	/home/afr/go/src/github.com/42wim/mm-go-irckit/user.go:137 +0xab
github.com/42wim/mm-go-irckit.(*server).handle(0xc8200d4c30, 0xc8200d4d00)
	/home/afr/go/src/github.com/42wim/mm-go-irckit/server.go:581 +0xb1
created by github.com/42wim/mm-go-irckit.(*server).Connect
	/home/afr/go/src/github.com/42wim/mm-go-irckit/server.go:282 +0xb5
```

I connected with weechat and the /msg mattermost login command worked fine. The crash happened at the following command (which contains a typo):

`/msg mattermost search queryt`

**Comment by 42wim** [comment] 2016-02-09 14:13
What mattermost version are you running ? Could be related to https://github.com/42wim/matterircd/issues/30 if you're running a mattermost < 1.4.0

**Comment by xyproto** [comment] 2016-02-10 12:52
This is the server I'm currently running:

```
Mattermost Team Edition

Version:1.4.0
Build Number:5302
Build Date:Thu Jan 21 14:34:38 UTC 2016
Build Hash:2fdfdaeff7a0bf29fd21eec6d4f48abe579d5048
```

**Comment by 42wim** [comment] 2016-02-10 19:15
Ok, I see the issue, you tried to search before you're actually logged in.

```
2016-02-09 09:57:21.530 DEBUG <- PRIVMSG mattermost :login mattermost afr password
2016-02-09 09:57:21.530 DEBUG -> :mattermost!mattermost@service PRIVMSG afr :need LOGIN <login> <pass>
```
You did ```login mattermost afr password``` instead of ```login afr password```

Nevertheless, it shouldn't crash on that, fixed in upcoming commit

**Closed** 2016-02-10 19:20 UTC

**Comment by dwest-galois** [comment] 2016-06-15 18:52
Hey, it looks like this issue may have returned.  I am running matterircd version 0.7 with Mattermost Enterprise Version: 3.0.0 (3.0.2).  If you perform a search while you are not logged in, then it will crash the service.  Did that fix get removed in later versions?

**Comment by xyproto** [comment] 2016-06-15 19:28
Does it work for you if you try [this docker image](https://hub.docker.com/r/xyproto/matterircd/)?

**Comment by dwest-galois** [comment] 2016-06-15 23:36
Yes, that docker image seems to work properly.  However, it looks like this is an older version.

Your host is matterircd, running version 0.3

But it is giving me the response I would expect

<mattermost> Can not search, you're not logged in. Use LOGIN first.

**Comment by 42wim** [comment] 2016-06-16 19:13
Thanks for reporting, was a regression caused by refactoring. Fixed in master.
