### ISSUE TITLE
Users falsely show as "away" (independently of their online status in Mattermost)

### ISSUE THREAD

**Issue by kkofler** [42wim/matterircd#268] opened 2020-03-19 10:18 UTC
I am using `matterircd` v0.19.4 with Mattermost 5.17.3. In my IRC client (Konversation 1.7.5), almost all nicknames are grayed out, i.e., the client thinks all users are away. Even myself. Only sometimes, for some reason, some user shows up as online (while other users that are online at the same time are still grayed out). The away status should reflect the status on Mattermost.

I also get the impression that #165 is still not fixed either, but I cannot reliably test that due to this issue.

**Comment by guilhermepiccoli** [comment] 2020-06-01 20:17
This is kind of a dupe of issue #147 right? I'm experiencing the same issue...
I think #147 was not fixed

**Comment by guilhermepiccoli** [comment] 2020-06-01 20:20
Interestingly, it seems I'm *not away* on Mattermost (I'm seen as available/online there), but I'm showing as away *on IRC*

**Comment by kkofler** [comment] 2020-06-01 22:27
> This is kind of a dupe of issue #147 right?

No, not quite. #147 was about `matterircd` users always showing as away to others. This one is about others almost always showing as away to `matterircd` users.

**Comment by guilhermepiccoli** [comment] 2020-06-02 12:09
OK, then perfect! In my experience, the problem is happening with myself: I'm showing as away on matterircd, but seems Online in mattermost. Some friends do show as online in IRC, and they are online in Mattermost...

**Comment by guilhermepiccoli** [comment] 2020-06-22 15:33
Related issue: issue #275

**Comment by 42wim** [comment] 2020-08-13 20:40
This should be fixed in master. (as in I can not reproduce this anymore)

**Closed by 42wim** 2020-08-13 20:40 UTC
